[project]
name = "numerical-methods"
version = "0.0.1"
requires-python = ">= 3.12"
dependencies = ["ruff", "numpy", "jax", "matplotlib", "tabulate"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]
